### ISSUE TITLE
Add a starfield nova_ecs plugin

### ISSUE THREAD

**Issue by mattsoulanille** [mattsoulanille/NovaJS#102]
This is probably a good first issue, but I need to document nova_ecs and its plugin system before tagging it as such.

NovaJS needs a starfield in the main branch. The alpha js demo has a working starfield that could be ported over, but its implementation is strange and inefficient. The original implementation used individual objects for each star and used a collision library (crash) to tell if they were on-screen. This implementation was complicated by slow-moving stars and used a complicated way to check if they were on-screen by varying the size of their hitbox based on how much they move with the ship. I only kind of understand how it works now, and it's almost certainly overcomplicated.

A much simpler and more efficient way to do this is to have several layers of stars that pan across the screen at different rates as the player moves around. The z position of stars would be discrete, but I'm guessing this would look okay with 8 or so layers. To make this more efficient than moving each star, we can generate a large random [starfield render texture](https://pixijs.download/release/docs/PIXI.RenderTexture.html) for each layer. That way the starfield only has to move 8 objects instead of every star that's on the screen. 

Some thoughts I have about how the implementation could work:
* Number of z layers should be configurable.
* Star density per square unit should be configurable.
* Minimum and maximum position factor (similar to z position in a 3d projection) relative to the player should be configurable with a maximum range of [0, 1)
  * Stars on a layer with position factor 0 have the same z position as the ship and planets and wouldn't move with the ship at all. In the ship's reference frame, they move the most.
  * Stars on a layer with position factor approaching 1 move perfectly with the ship and look like they are at z = infinity i.e. infinitely far away. In the ship's reference frame, they don't move at all.
  * Layers should (probably) be evenly spaced within the range.
  * The position factor of a layer determines the layer's texture size. A layer with position factor 0 needs to be as large as the system wraparound dimensions. A layer with position factor 0.5 only needs to be half as large on a side as the wraparound dimensions (since the stars move with the ship at 1/2 the ship's speed). Very small position factors can run into issues if the user's screen is larger than the computed texture, but this can be fixed by tiling, I think (although that has the potential to look repetitive in the case of really small factors, but that's probably not going to be a problem).
  * If 'position factor' is awkward, we can use `1 - position factor` and call it something else, or we can use `z` and have it scale from [0, infinity) (which might be more intuitive).
* Distribution of stars should probably not be uniform in the z direction because that would make there be a lot more far-away stars than close stars. I'm guessing that layers which are "farther away" i.e. have a larger position factor will (I think) need to have fewer stars total than layers that are "closer" i.e. have a smaller position factor. Stars per unit of square texture area of a layer should be the same for each layer, I think.
* When a ship wraps around the system border, the stars ideally shouldn't appear different. This can probably be achieved by [tiling](https://pixijs.io/examples/#/sprite/tiling-sprite.js) the starfield sprites.

**Comment by CodyMWilson** [comment]
I went to start this yesterday but I've gotten stuck with the run step - I can't get my browser to display the project. I think this might be because I'm using Ubuntu on WSL2 for Windows.

**Comment by mattsoulanille** [comment]
This is probably not helpful to hear, but it seems to work for me in WSL2 :P
![wsl2-novajs](https://user-images.githubusercontent.com/1474501/113465457-15b59800-9402-11eb-9f82-b07766b3446a.png)

* Is your browser pointing to http://localhost:8000?
* Is port 8000 in use on your machine on the windows side? You can change the port NovaJS uses in `nova/settings/server.json`.
* When you run novajs, if you press enter, do you see the prompt `nova>`? 

Even if you have no nova files or plugins installed, it should still give you a default ship that can fly around. Maybe there's a setting in WSL2 that has to be set to allow it to bind to ports, and it was automatically set for me? 

I was able to connect with a browser (Edge, but that shouldn't matter) on the same machine, but I wasn't able to connect from a different machine.

I also tried building the project outside of wsl2 using git bash etc., and only parts of it work in that environment. I can run the tests for `nova_ecs` but anything that accesses the filesystem seems to be broken due (I think) to paths working differently on windows, so wsl2 seems like the best way to run it. If that's a bad development environment, I can try to get it working in git bash.

**Comment by CodyMWilson** [comment]
I got it to work! The only command that works for me at the moment is

`sudo npm run run`

I also had to make a change on chrome settings to allow unsigned connections from localhost and I added a rule via a suggestion on StackExchange to allow port 8000 connections. I have to admit that I'm not sure which change fixed it as I made these changes with no success and the next day I came to the project it worked with no additional changes. I'm thinking that a reboot was necessary. 

Some other things I ran into:

`yarn start` complains that there is no startup script
I also tried running the NovaJS directory (as opposed to the alpha directory)
`sudo npm run build` complains that 
> novajs@0.1.0 build
> bazelisk build //...
> sh: 1: bazelisk: not found

From what I can glean, bazel has issues with wsl2, but this didn't stop npm from running. 

Again I'm not 100% understanding of all the technologies used here so there's probably something I'm glossing over :) 
Thanks for your input!

![image](https://user-images.githubusercontent.com/17019631/113486425-7a570e00-9467-11eb-9a05-df6f557e6451.png)

**Comment by mattsoulanille** [comment]
I'm glad you got it working, but I think you're using the legacy js version instead of the typesctipt rewrite. Are you using your fork or the legacy js release zip downloadable from the releases page? While the js version is more feature conplete, I wrote it while not very experienced at programming, and it's core design is not very good. 

I'm rewriting it in typescript with an architecture based on an entity component system, but I only have the basics of ship flight working at the moment. There may be some degree of second system effect happening, but I really do think the js version's design is fundamentally flawed for a number of reasons (uses mixins, complicated inheritance chains ...). I'll go into more detail later, but I'm on mobile right now.

**Comment by CodyMWilson** [comment]
This is my result from running yarn. 

`sudo yarn`

>00h00m00s 0/0: : ERROR: There are no scenarios; must have at least one.

`yarn --version`

>0.32+git

Interestingly I was running the wrong yarn. According to the [StackExchange ](https://stackoverflow.com/questions/53471063/yarn-error-there-are-no-scenarios-must-have-at-least-one)post that helped me solve the issue:

> You've got the wrong yarn. The yarn you're executing comes from the cmdtest package. Uninstalling cmdtest first should fix this:
> 
> sudo apt remove cmdtest
> 
> Once you've uninstalled it, run the commands below to install yarn properly:
> 
> curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | sudo apt-key add -
> echo "deb https://dl.yarnpkg.com/debian/ stable main" | sudo tee /etc/apt/sources.list.d/yarn.list
> sudo apt update
> sudo apt install yarn

After that things seem to be working well.
`yarn`

> yarn install v1.22.5
> [1/5] Validating package.json...
> [2/5] Resolving packages...
> [3/5] Fetching packages...
> info fsevents@2.3.2: The platform "linux" is incompatible with this module.
> info "fsevents@2.3.2" is an optional dependency and failed compatibility check. Excluding it from installation.
> [4/5] Linking dependencies...
> warning " > io-ts-types@0.5.16" has unmet peer dependency "monocle-ts@^2.0.0".
> warning " > io-ts-types@0.5.16" has unmet peer dependency "newtype-ts@^0.3.2".
> [5/5] Building fresh packages...
> Done in 15.84s.
> cody@Blade:~/dev/git/NovaJS$ yarn watch
> yarn run v1.22.5
> $ ibazel run nova
> iBazel [1:24PM]: Running `bazel info`... it's being a little slow
> iBazel [1:24PM]: Querying for files to watch...
> Loading: 0 packages loaded
> Loading: 180 packages loaded
> Loading: 183 packages loaded
> 
> Loading: 183 packages loaded
> Loading: 0 packages loaded
> Loading: 0 packages loaded
> 
> Loading: 0 packages loaded
> iBazel [1:24PM]: Running nova
> Loading:
> Loading: 0 packages loaded
> Analyzing: target //nova:nova (0 packages loaded, 0 targets configured)
> Analyzing: target //nova:nova (8 packages loaded, 7 targets configured)
> Analyzing: target //nova:nova (8 packages loaded, 7 targets configured)
> Analyzing: target //nova:nova (8 packages loaded, 7 targets configured)
> Analyzing: target //nova:nova (8 packages loaded, 7 targets configured)
> Analyzing: target //nova:nova (8 packages loaded, 7 targets configured)
> Analyzing: target //nova:nova (8 packages loaded, 7 targets configured)
> Analyzing: target //nova:nova (8 packages loaded, 7 targets configured)
> Analyzing: target //nova:nova (8 packages loaded, 7 targets configured)
> Analyzing: target //nova:nova (8 packages loaded, 7 targets configured)
> Analyzing: target //nova:nova (8 packages loaded, 7 targets configured)
> Analyzing: target //nova:nova (8 packages loaded, 7 targets configured)
> Analyzing: target //nova:nova (8 packages loaded, 7 targets configured)
> INFO: Analyzed target //nova:nova (14 packages loaded, 7421 targets configured).
> INFO: Found 1 target...
> 
> INFO: Elapsed time: 19.768s
> INFO: 0 processes.
> INFO: Build completed successfully, 0 total actions
> INFO: Build completed successfully, 0 total actions
> Loading:
> Loading: 0 packages loaded
> Analyzing: target //nova:nova (0 packages loaded, 0 targets configured)
> INFO: Analyzed target //nova:nova (0 packages loaded, 0 targets configured).
> INFO: Found 1 target...
> [0 / 6] [Prepa] BazelWorkspaceStatusAction stable-status.txt ... (5 actions, 0 running)
> [85 / 130] [Sched] Compiling TypeScript (prodmode) //nova_ecs:ecs ... (7 actions, 4 running)
> [86 / 130] [Sched] Compiling TypeScript (devmode) //nova_ecs:ecs ... (8 actions, 4 running)
> [90 / 130] Compiling TypeScript (prodmode) //nova_ecs/datatypes:datatypes; 3s worker ... (5 actions, 4 running)
> [94 / 130] Compiling TypeScript (prodmode) //nova_ecs:ecs; 2s worker ... (3 actions, 2 running)
> [96 / 130] Compiling TypeScript (prodmode) //nova_ecs:ecs; 3s worker ... (8 actions, 4 running)
> [100 / 130] Compiling TypeScript (devmode) //nova_ecs:ecs; 4s worker ... (6 actions, 4 running)
> [106 / 130] Compiling TypeScript (devmode) //nova_ecs/plugins:plugins; 0s worker ... (4 actions running)
> [111 / 130] Compiling TypeScript (devmode) //nova_ecs/plugins:plugins; 2s worker
> [115 / 130] Compiling TypeScript (devmode) //nova/src/nova_plugin:nova_plugin; 1s worker ... (7 actions, 4 running)
> [120 / 130] Compiling TypeScript (devmode) //nova/src/communication:communication_client_lib; 1s worker ... (4 actions running)
> [126 / 130] Compiling TypeScript (devmode) //nova/src:browser_lib; 0s worker ... (3 actions running)
> INFO: From Bundling Javascript nova/server.mjs [esbuild]:
>  > bazel-out/k8-fastbuild/bin/nova/server.mjs: warning: This call to "require" will not be bundled because the argument is not a string literal (surround with a try/catch to silence this warning)
>     35 │ const runfiles = require(process.env.BAZEL_NODE_RUNFILES_HELPER);
>        ╵                  ~~~~~~~
> 
>  > external/npm/node_modules/express/lib/view.js: warning: This call to "require" will not be bundled because the argument is not a string literal (surround with a try/catch to silence this warning)
>     81 │     var fn = require(mod).__express
>        ╵              ~~~~~~~
> 
> 2 warnings
> Target //nova:nova up-to-date:
>   dist/bin/nova/nova.sh
>   dist/bin/nova/nova_loader.js
>   dist/bin/nova/nova_require_patch.js
> INFO: Elapsed time: 17.330s, Critical Path: 16.38s
> INFO: 130 processes: 85 internal, 4 linux-sandbox, 41 worker.
> INFO: Build completed successfully, 130 total actions
> INFO: Build completed successfully, 130 total actions
> iBazel [1:25PM]: Starting...
> 
> ################################################################################
> # Did you know iBazel can invoke programs like Gazelle, buildozer, and         #
> # other BUILD file generators for you automatically based on bazel output?     #
> # Documentation at: https://github.com/bazelbuild/bazel-watcher#output-runner  #
> ################################################################################
> 
> nova> No such client server
> listening at port 8000

**Comment by mattsoulanille** [comment]
Oh right, I forgot that `yarn` is a different program on Ubuntu, and the yarn you want is actually `yarnpkg`, but it looks like the fix you found should work too. Sorry! I'll add that to the readme. The logs you're seeing now look right for the up-to-date TypeScript version.

One way to tell the difference between the typescript version and the js version is that the typescript one uses bazel. If you see bazel or bazelisk in the logs, you're on the typescript version. You can also run `git branch`, and if you're on the `main` branch, that's the typescript version. The `js` version's branch was called `master`. Also, if you see a `WORKSPACE` file or `BUILD.bazel` files, that's the typescript version.

**Comment by CodyMWilson** [comment]
I was about to ask what the difference between main and master is but then I googled it and _duh_ now it makes sense (we ran into this for our code at my workplace earlier this year too).

> GitHub is working on replacing the term "master" on its service with a neutral term like "main" to avoid any unnecessary references to slavery,

**Comment by mattsoulanille** [comment]
I've added some documentation to [nova_ecs](https://github.com/mattsoulanille/NovaJS/tree/main/nova_ecs) and written a brief overview of the project's structure in the main README. It's not complete enough to really explain how the project works, but hopefully it'll give some idea of the structure.

I've also [created](https://github.com/mattsoulanille/NovaJS/pull/106) a simple example starfield with no depth and no automatic tiling (and the wrong dimensions and position) in [`starfield_plugin.ts`](https://github.com/mattsoulanille/NovaJS/blob/main/nova/src/display/starfield_plugin.ts). It should have everything needed for the real starfield to work correctly.

**Comment by CodyMWilson** [comment]
> NovaJS needs a starfield. The original implementation used individual objects for each star and used a collision library (crash) to tell if they were on-screen. This implementation was complicated by slow-moving stars, since instead of changing their position, it changed their collision hitbox based on the screen size. I only kind of understand how it works now, and it's almost certainly overcomplicated.

Was there a need to have a hitbox collision system for the starfield? I thought that things in the starfield would never be interacted by the players ship (at least that's how I remember it - are there exemptions to this?) Even planets would be distinct from the players ship. Or am I not understanding the meaning of 'collide'?

Also (out of curiosity) is this an enhancement to the original game? It looked like the background layer was already working in the example - is this adding additional layers to that or completely reworking it? Or is there only a single layer there at the moment?

Lots of questions because I've never heard of a lot of these terms, but perhaps these will be helpful for others as well.

**Comment by mattsoulanille** [comment]
The background layer / starfield is working in the alpha js version, but the typescript version doesn't have a starfield yet. I was considering just copying the js version's starfield over, but it's such a weird implementation that I though it needed a rewrite. Sorry if I didn't make that clear in the issue description. I've updated it.

There is no need for each star in the starfield to have a hitbox. The original starfield implementation was rather strange. It used an individual sprite for each star and would move every star (of which there were thousands) every frame. This caused the game to lag, so as a fix, I created a collision hitbox for the player's viewport and for each star. Then, if a star collided with the viewport, that meant it was on-screen, and I would have PIXI display it. Otherwise, it would be hidden to improve performance. The collision engine used a quadtree, so it was able to check which stars were on-screen without looping over all of them, hence the performance boost. 

The actual implementation, however, was much more complicated due to slow-moving stars. In order to get the performance benefits of the collision library, I had to avoid manually looping over all the stars and moving them every frame. I solved this by varying the size of the star's hitbox relative to how much it tracked with the ship, since stars that moved with the ship more would stay on screen for longer and would therefore need a larger hitbox. I'm not really explaining this well since I only sort of understand it myself.

The performance fix of using a collision engine to check for on-screen stars, while good enough to make the game not lag, is still rather inefficient. It still checks and moves a large number of stars every frame where the layers method would only have to move each layer every frame. The larger problem is I only sort of understand how it works, and I don't really want to spend the effort to understand it again when there's a simpler, more efficient solution that also fixes the clipping issue at the edge of a system. That's why I think it could use a rewrite for the typescript version.

No worries about the number of questions! I'm happy to answer them! Also, I think the plan I wrote out in the issue description should work, but it's entirely possible I've made several mistakes in it. I've never used tiling sprites before. If anything about it doesn't make sense about it, it's quite possibly wrong.

**Comment by CodyMWilson** [comment]
> so as a fix, I created a collision hitbox for the player's viewport and for each star. Then, if a star collided with the viewport, that meant it was on-screen, and I would have PIXI display it.

Ah! Makes a lot of sense now.

Your plan seems decent! I'll let you know how it goes

**Comment by mattsoulanille** [comment]
I thought about this again and realized we would have to make textures that are around 10,000 x 10,000, which would not fit on the GPU. There was also an attempt at a shader-based version that showed promise on high-end gpus, but it was far too slow on laptops. I've reimplemented the original design, which I now realize was likely the right way to go from the start, as strange as it is with how it uses rbush.

**Comment by CodyMWilson** [comment]
@mattsoulanille Nice! I opened the demo, it works really well. 
I started looking into the starfield but ended up confused. 
I was curious - what would it take (and do you have design ideas) for getting hyperspace jumping to work (AKA loading other systems)?

**Comment by mattsoulanille** [comment]
@CodyMWilson Hyperspace jumping should actually be working now! I got it working a few days ago in https://github.com/mattsoulanille/NovaJS/pull/327. You can press `m` to open the map and select a system to jump to. There's no jump animation yet, but `j` should take you to the next system.

**Comment by CodyMWilson** [comment]
@mattsoulanille That's so rad! Anything else you could use help with?
